# Generated by Django 4.2 on 2023-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_alter_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.TimeField(),
        ),
    ]
