# Generated by Django 4.2 on 2023-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0007_article_date_alter_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
