# Generated by Django 4.2 on 2023-04-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0010_alter_article_date_alter_article_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
