# Generated by Django 4.2 on 2023-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0011_delete_excelfile_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
