# Generated by Django 4.2 on 2023-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
