# Generated by Django 4.2 on 2023-04-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0002_alter_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
