# Generated by Django 4.2 on 2023-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0003_sporttype_image_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
